apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
data:
  index.html: |
    <html>
    <h1 style="background-color:red;">Service2</h1>
    </html>
