apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echo-service-ingress
spec:
  hosts: 
  - "service.com"    # this is what the client refers to the host
  gateways:
  - echo-gateway
  http:
  - route:
    - destination:
        host: service   #these are the actual kubernetes service
        subset: v1
      weight: 50
    - destination:
        host: service
        subset: v3
      weight: 50
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: echo-service-ingress
spec:
  host: service    #this is a kube service..and we are defining what to do with traffic which comes for this service.
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v3
    labels:
      version: v3